"""Media format matrix: every advertised upload format ends up with a type the browser plays.

DEFECT THIS CATCHES (issue #1044): the stored ``media_file.content_type`` was the
uploading browser's ``File.type``, verbatim. On Linux with shared-mime-info >= 2.4
Firefox reports ``audio/vnd.wave`` for ``*.wav`` (Python 3.14's ``mimetypes`` does the
same), and the player's ``<source type="audio/vnd.wave">`` is rejected by Firefox and
Chromium alike (``canPlayType`` returns ``""``), so a WAV that transcribed fine showed
00:00 and never played. The bytes were never the problem; only the label was.

Each case uploads a REAL file generated by ffmpeg at test time, declared with every
MIME alias a browser, OS MIME database, or Python ``mimetypes`` is known to emit for it,
and asserts:

(a) the stored type is the canonical, browser-accepted form, both on the row and on the
    object written to storage, for the legacy ``POST /files`` route and the
    presigned ``POST /files/prepare`` route;
(b) ``/stream-url`` reports the canonical type and signs it into the presigned GET as
    ``response-content-type``, including for rows stored with an alias before the fix.

Which types browsers accept was measured, not assumed: Playwright Firefox and
Chromium were given each fixture as ``<source type=X>`` and with no type. The results
are recorded per case below. Formats no browser decodes (AVI, AIFF) are marked
``needs_transcode``. Normalising them keeps the data consistent but cannot make them
play.
"""

from __future__ import annotations

import io
import shutil
import subprocess
import uuid
from dataclasses import dataclass
from pathlib import Path
from unittest import mock

import pytest
from fastapi import status

from app.models.media import MediaFile

_AUDIO_IN = ["-f", "lavfi", "-i", "sine=frequency=440:duration=0.5:sample_rate=16000"]
_VIDEO_IN = ["-f", "lavfi", "-i", "color=c=blue:s=64x64:d=0.5:r=10", *_AUDIO_IN]
_H264_AAC = ["-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest"]


@dataclass(frozen=True)
class MediaFormat:
    ext: str
    ffmpeg_args: tuple[str, ...]
    # Every declared type seen in the wild for this format. The first is canonical.
    declared: tuple[str, ...]
    canonical: str
    # No mainstream browser decodes it (measured); playback would need a transcode.
    needs_transcode: bool = False


FORMATS: tuple[MediaFormat, ...] = (
    MediaFormat(
        "mp3", (*_AUDIO_IN, "-c:a", "libmp3lame"), ("audio/mpeg", "audio/mp3"), "audio/mpeg"
    ),
    MediaFormat(
        "wav",
        (*_AUDIO_IN, "-c:a", "pcm_s16le"),
        # audio/vnd.wave: shared-mime-info >= 2.4 (Firefox on Linux) and Python 3.14.
        # audio/wave: rejected by Chromium's canPlayType.
        ("audio/wav", "audio/vnd.wave", "audio/x-wav", "audio/wave"),
        "audio/wav",
    ),
    MediaFormat("ogg", (*_AUDIO_IN, "-c:a", "libvorbis"), ("audio/ogg",), "audio/ogg"),
    MediaFormat(
        "opus",
        (*_AUDIO_IN, "-c:a", "libopus", "-ar", "48000"),
        # audio/opus is what mimetypes gives for *.opus; both browsers reject it as a
        # <source type> but play the same Ogg bytes labelled audio/ogg.
        ("audio/ogg", "audio/opus"),
        "audio/ogg",
    ),
    MediaFormat(
        "flac",
        (*_AUDIO_IN, "-c:a", "flac"),
        ("audio/flac", "audio/x-flac"),  # Chromium rejects audio/x-flac
        "audio/flac",
    ),
    MediaFormat(
        "aac",
        (*_AUDIO_IN, "-c:a", "aac", "-f", "adts"),
        ("audio/aac", "audio/x-aac", "audio/aacp"),  # Chromium rejects the aliases
        "audio/aac",
    ),
    MediaFormat(
        "m4a",
        (*_AUDIO_IN, "-c:a", "aac"),
        # audio/m4a and audio/mp4a-latm are rejected by both browsers.
        ("audio/mp4", "audio/x-m4a", "audio/m4a", "audio/mp4a-latm"),
        "audio/mp4",
    ),
    MediaFormat("mp4", (*_VIDEO_IN, *_H264_AAC), ("video/mp4",), "video/mp4"),
    MediaFormat(
        "webm",
        (*_VIDEO_IN, "-c:v", "libvpx-vp9", "-c:a", "libopus", "-ar", "48000", "-shortest"),
        ("video/webm",),
        "video/webm",
    ),
    # QuickTime is stored truthfully. Chromium rejects it as a <source type> but plays
    # an H.264 .mov with no type hint, so the player omits the hint (frontend matrix).
    MediaFormat("mov", (*_VIDEO_IN, *_H264_AAC), ("video/quicktime",), "video/quicktime"),
    MediaFormat(
        "mkv",
        (*_VIDEO_IN, *_H264_AAC),
        ("video/x-matroska", "video/matroska"),  # video/matroska: Python 3.14
        "video/x-matroska",
    ),
    MediaFormat(
        "avi",
        (*_VIDEO_IN, "-c:v", "mpeg4", "-c:a", "libmp3lame", "-shortest"),
        ("video/x-msvideo", "video/vnd.avi", "video/avi"),  # video/vnd.avi: Python 3.14
        "video/x-msvideo",
        needs_transcode=True,
    ),
    MediaFormat(
        "aiff",
        (*_AUDIO_IN, "-c:a", "pcm_s16be"),
        ("audio/x-aiff", "audio/aiff"),
        "audio/x-aiff",
        needs_transcode=True,
    ),
)

_DECLARED_CASES = [
    pytest.param(fmt, declared, id=f"{fmt.ext}-{declared}")
    for fmt in FORMATS
    for declared in fmt.declared
]


@pytest.fixture(scope="module")
def media_fixtures(tmp_path_factory) -> dict[str, bytes]:
    """Generate one tiny real file per format (~0.5 s, a few KB each)."""
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg is required to generate the media format fixtures")
    out_dir: Path = tmp_path_factory.mktemp("media_formats")
    fixtures: dict[str, bytes] = {}
    for fmt in FORMATS:
        path = out_dir / f"sample.{fmt.ext}"
        subprocess.run(
            ["ffmpeg", "-loglevel", "error", "-y", *fmt.ffmpeg_args, str(path)],
            check=True,
            timeout=60,
        )
        fixtures[fmt.ext] = path.read_bytes()
    return fixtures


def _stored_type(db_session, file_uuid: str) -> str | None:
    """The content_type persisted on the row, read fresh from the database."""
    db_session.expire_all()
    row: MediaFile = db_session.query(MediaFile).filter(MediaFile.uuid == file_uuid).one()
    return row.content_type


@pytest.mark.parametrize(("fmt", "declared"), _DECLARED_CASES)
def test_legacy_upload_stores_canonical_type(
    client, user_token_headers, db_session, media_fixtures, fmt, declared
):
    """(a) ``POST /files``: row AND the stored object carry the canonical type."""
    stored_types: list[str] = []

    def _capture(_content, _size, _path, content_type):
        stored_types.append(content_type)

    with mock.patch("app.api.endpoints.files.upload.upload_file_to_storage", side_effect=_capture):
        response = client.post(
            "/api/files",
            headers=user_token_headers,
            files={
                "file": (
                    f"sample.{fmt.ext}",
                    io.BytesIO(media_fixtures[fmt.ext]),
                    declared,
                )
            },
        )

    assert response.status_code == status.HTTP_200_OK, response.text
    assert _stored_type(db_session, response.json()["uuid"]) == fmt.canonical
    assert stored_types == [fmt.canonical]


@pytest.mark.parametrize(("fmt", "declared"), _DECLARED_CASES)
def test_prepare_upload_stores_canonical_type(
    client, user_token_headers, db_session, media_fixtures, fmt, declared
):
    """(a) ``POST /files/prepare`` (the browser-direct path) stores the canonical type."""
    response = client.post(
        "/api/files/prepare",
        headers=user_token_headers,
        json={
            "filename": f"sample.{fmt.ext}",
            "file_size": len(media_fixtures[fmt.ext]),
            "content_type": declared,
        },
    )

    assert response.status_code == status.HTTP_200_OK, response.text
    assert _stored_type(db_session, response.json()["file_id"]) == fmt.canonical


@pytest.mark.parametrize(("fmt", "declared"), _DECLARED_CASES)
def test_browser_direct_upload_plan_uses_canonical_type(
    client, user_token_headers, media_fixtures, monkeypatch, fmt, declared
):
    """(a) The browser-direct upload plan fixes a multipart object's Content-Type at
    initiation, so ``/files/prepare`` must hand it the canonical type, not the alias."""
    from app.services import multipart_upload

    planned_with: list[str | None] = []

    def _plan(_object_name, content_type, _file_size):
        planned_with.append(content_type)
        return {"upload_method": "PUT", "http_flow": "presigned", "upload_url": "https://x"}

    monkeypatch.setattr(multipart_upload, "build_upload_plan", _plan)

    response = client.post(
        "/api/files/prepare",
        headers=user_token_headers,
        json={
            "filename": f"sample.{fmt.ext}",
            "file_size": len(media_fixtures[fmt.ext]),
            "content_type": declared,
            "use_presigned": True,
        },
    )

    assert response.status_code == status.HTTP_200_OK, response.text
    assert planned_with == [fmt.canonical]


@pytest.mark.parametrize(("fmt", "declared"), _DECLARED_CASES)
def test_stream_url_serves_canonical_type(
    client, user_token_headers, normal_user, db_session, monkeypatch, fmt, declared
):
    """(b) Rows stored with an alias BEFORE this fix still play: ``/stream-url``
    reports the canonical type and signs it into the presigned GET."""
    file_uuid = str(uuid.uuid4())
    db_session.add(
        MediaFile(
            uuid=file_uuid,
            filename=f"sample.{fmt.ext}",
            title="sample",
            storage_path=f"media/test/{file_uuid}.{fmt.ext}",
            content_type=declared,
            file_size=4096,
            status="completed",
            is_public=False,
            user_id=normal_user.id,
        )
    )
    db_session.commit()

    signed: list[dict | None] = []

    class _FakePresignClient:
        def presigned_get_object(self, bucket_name, object_name, expires, response_headers=None):
            signed.append(response_headers)
            return f"https://storage.example.test/{bucket_name}/{object_name}?X-Amz-Signature=x"

    from app.services import storage_presign_identity

    monkeypatch.setenv("SKIP_S3", "False")
    monkeypatch.setattr(storage_presign_identity, "presign_client", _FakePresignClient)

    response = client.get(
        f"/api/files/{file_uuid}/stream-url",
        params={"media_type": "video"},
        headers=user_token_headers,
    )

    assert response.status_code == status.HTTP_200_OK, response.text
    assert response.json()["content_type"] == fmt.canonical
    assert signed == [{"response-content-type": fmt.canonical}]


def test_firefox_wav_upload_is_stored_as_audio_wav(
    client, user_token_headers, db_session, sample_wav_bytes
):
    """The exact reported case: Firefox on Linux declares a WAV as ``audio/vnd.wave``."""
    with mock.patch("app.api.endpoints.files.upload.upload_file_to_storage"):
        response = client.post(
            "/api/files",
            headers=user_token_headers,
            files={
                "file": ("ES2005a.Mix-Headset.wav", io.BytesIO(sample_wav_bytes), "audio/vnd.wave")
            },
        )

    assert response.status_code == status.HTTP_200_OK, response.text
    assert _stored_type(db_session, response.json()["uuid"]) == "audio/wav"
