/**
 * Compile the minimal, LGPL-2.1+-only FFmpeg.wasm core into `static/ffmpeg/` (issue #473)
 * so the production image can serve `/ffmpeg/*` itself instead of reaching out to a CDN
 * at build time.
 *
 * Previously this fetched the generic, full-featured `@ffmpeg/core` from unpkg — which is
 * GPL 2+ (built with --enable-gpl --enable-libx264 --enable-libx265 etc), not the LGPL
 * 2.1+ the FFmpeg project defaults to. `audioExtractionService.ts` only ever runs `-c
 * copy` (stream copy, no decode/encode/filter), which needs none of that: a vanilla
 * FFmpeg build with zero external codec libraries and zero GPL flags covers our exact use
 * case. See `ffmpeg-wasm-build/PROVENANCE.md` for the full story and
 * `ffmpeg-wasm-build/configure-summary.txt` (generated by the build) for the verified
 * license.
 *
 * `static/ffmpeg/` is gitignored (the compiled core is a couple MB), so without this
 * prebuild step a clean checkout builds an image with no `/ffmpeg/*` at all and
 * client-side audio extraction fails at load time. Same pattern as `download-fonts.js`:
 * extraction is an optional, lazily-loaded feature, so a failed/skipped build warns and
 * lets `npm run build` continue rather than killing it (no-Docker / air-gapped hosts).
 *
 * The production Docker image does NOT use this script — `Dockerfile.prod` compiles the
 * same core as its own build stage (kept in sync by hand, see the comment there). This
 * script exists for local/dev builds (`./opentr.sh start dev` bind-mounts source and never
 * runs `Dockerfile.prod`) and `npm run build` run directly on the host.
 */
import { existsSync, mkdirSync, statSync, copyFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ffmpegDir = join(__dirname, '../static/ffmpeg');
const buildDir = join(__dirname, '../ffmpeg-wasm-build');
const builtDir = join(buildDir, 'dist/dist/esm');

// Sized against the actual demux+mux-only build (~200 KB JS / ~2.2 MB wasm) — far smaller
// than the old generic CDN build's ~31 MB, since we compile in zero external codec libs
// and zero encoders/decoders (bar one native AAC decoder used only for probing). The floor
// still exists to catch a truncated/partial build, same purpose as the old download check.
const CORE_FILES = [
  { name: 'ffmpeg-core.js', minBytes: 100_000 },
  { name: 'ffmpeg-core.wasm', minBytes: 1_500_000 },
];

function isValid() {
  return CORE_FILES.every(({ name, minBytes }) => {
    const target = join(ffmpegDir, name);
    return existsSync(target) && statSync(target).size >= minBytes;
  });
}

function hasDocker() {
  const check = spawnSync('docker', ['buildx', 'version'], { stdio: 'ignore' });
  return check.status === 0;
}

function build() {
  console.log('Compiling minimal FFmpeg.wasm core (this is cached — subsequent runs skip it)...');
  const result = spawnSync('bash', ['build.sh'], { cwd: buildDir, stdio: 'inherit' });
  if (result.status !== 0) {
    throw new Error(`ffmpeg-wasm-build/build.sh exited with code ${result.status}`);
  }
}

async function main() {
  if (!existsSync(ffmpegDir)) {
    mkdirSync(ffmpegDir, { recursive: true });
  }

  if (isValid()) {
    console.log(`FFmpeg.wasm core already present in ${ffmpegDir}`);
    return;
  }

  if (!hasDocker()) {
    console.warn(
      'Warning: Docker (with buildx) is required to compile the FFmpeg.wasm core and was ' +
        'not found. Client-side audio extraction will be unavailable in this build.'
    );
    return;
  }

  try {
    build();
    for (const { name } of CORE_FILES) {
      copyFileSync(join(builtDir, name), join(ffmpegDir, name));
    }
    if (!isValid()) {
      throw new Error('build completed but output files are missing or under the size floor');
    }
    console.log(`FFmpeg.wasm core built and copied into ${ffmpegDir}`);
  } catch (error) {
    console.warn(
      `Warning: could not build the FFmpeg.wasm core (${error.message}). ` +
        'Client-side audio extraction will be unavailable in this build.'
    );
  }
}

main();
