import Layout from '@theme/Layout';
import clsx from 'clsx';
import React, {type JSX} from 'react';

import roadmap from '../data/roadmap.json';
import styles from './roadmap.module.css';

/**
 * Public roadmap.
 *
 * The data is generated by `scripts/generate-roadmap.py` from GitHub issues — epic
 * labels group, milestones version, issue state is progress. Nothing here is hand
 * maintained, so the page cannot describe work that is not tracked.
 *
 * Structure follows the prior art rather than being invented: a vertical timeline of
 * releases with terse summaries and links out to the issues (Immich), release-oriented
 * rather than Kanban (Rust, GitHub's own roadmap), and now/next/later stage labels
 * instead of dates — which Immich's own community asked them for, because a date the
 * project cannot honour is worse than no date.
 */

type Issue = {number: number; title: string; done: boolean};
type Area = {
  key: string;
  name: string;
  scope: string;
  known: boolean;
  total: number;
  closed: number;
  issues: Issue[];
};
type Release = {
  version: string;
  headline: string;
  summary: string;
  stage: string;
  scheduled: boolean;
  total: number;
  closed: number;
  areas: Area[];
};

const STAGE_LABEL: Record<string, string> = {
  now: 'In progress',
  next: 'Up next',
  later: 'Later',
  // "complete" is every issue closed but no git tag yet — the work is done, the
  // release is not out. Calling that "Shipped" would announce a release that does
  // not exist.
  complete: 'Ready to ship',
  shipped: 'Shipped',
};

function issueUrl(n: number): string {
  return `https://github.com/${roadmap.repo}/issues/${n}`;
}

function labelUrl(key: string): string {
  return `https://github.com/${roadmap.repo}/labels/${encodeURIComponent(`epic:${key}`)}`;
}

function Progress({closed, total, done}: {closed: number; total: number; done: boolean}) {
  // Guard the divide: an empty milestone is possible (a release with every issue
  // moved out) and NaN% renders as a full bar, which reads as "complete".
  const pct = total === 0 ? 0 : Math.round((closed / total) * 100);
  return (
    <div className={styles.progressRow}>
      <div className={styles.track}>
        <div
          className={clsx(styles.fill, done && styles.fillDone)}
          style={{width: `${pct}%`}}
          role="progressbar"
          aria-valuenow={closed}
          aria-valuemin={0}
          aria-valuemax={total}
          aria-label={`${closed} of ${total} issues complete`}
        />
      </div>
      <span className={styles.count}>
        {closed}/{total}
      </span>
    </div>
  );
}

function ReleaseEntry({release}: {release: Release}) {
  const done = release.stage === 'shipped' || release.stage === 'complete';
  const now = release.stage === 'now';
  const label = STAGE_LABEL[release.stage] ?? 'Unscheduled';
  const headline = release.headline || 'Not yet scheduled';
  const summary =
    release.summary ||
    'Tracked and grouped, but not assigned to a release. These move into a version as ' +
      'the work ahead of them lands.';

  return (
    <section
      className={clsx(styles.entry, now && styles.entryNow, done && styles.entryDone)}
      aria-labelledby={`release-${release.version}`}
    >
      <div className={styles.head}>
        <h2 className={styles.version} id={`release-${release.version}`}>
          {release.scheduled ? release.version : 'Backlog'}
        </h2>
        <span className={styles.headline}>{headline}</span>
        <span className={clsx(styles.stage, now && styles.stageNow, done && styles.stageDone)}>
          {label}
        </span>
      </div>

      <p className={styles.summary}>{summary}</p>

      <Progress closed={release.closed} total={release.total} done={done} />

      <div className={styles.areas}>
        {release.areas.map((area) => (
          <div className={styles.area} key={area.key}>
            <a className={styles.areaName} href={labelUrl(area.key)} title={area.scope}>
              {area.name}
            </a>
            <span className={styles.areaCount}>
              {area.closed}/{area.total}
            </span>
          </div>
        ))}
      </div>

      <details className={styles.details}>
        <summary>
          {release.total} {release.total === 1 ? 'issue' : 'issues'}
        </summary>
        {release.areas.map((area) => (
          <div className={styles.issueGroup} key={area.key}>
            <div className={styles.issueGroupName}>{area.name}</div>
            <ul className={styles.issueList}>
              {area.issues.map((issue) => (
                <li
                  className={clsx(styles.issue, issue.done && styles.issueDone)}
                  key={issue.number}
                >
                  <span className={styles.issueNumber} aria-hidden="true">
                    {issue.done ? '✓' : '○'}
                  </span>
                  <span className={styles.issueTitle}>
                    <a href={issueUrl(issue.number)}>#{issue.number}</a> {issue.title}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </details>
    </section>
  );
}

export default function Roadmap(): JSX.Element {
  const releases = roadmap.releases as Release[];

  return (
    <Layout
      title="Roadmap"
      description="What is being built in OpenTranscribe, by release, generated from GitHub issues."
    >
      <header className={styles.hero}>
        <h1 className={styles.title}>Roadmap</h1>
        <p className={styles.subtitle}>
          What is being built, by release. Every item is a GitHub issue — this page is generated
          from the tracker, so it cannot describe work that is not tracked.
        </p>
        <div className={styles.heroLinks}>
          <a href={roadmap.project}>Project board</a>
          <a href={`https://github.com/${roadmap.repo}/milestones`}>Milestones</a>
          <a href={`https://github.com/${roadmap.repo}/issues`}>All issues</a>
        </div>
      </header>

      <main className={styles.timeline}>
        {releases.map((release) => (
          <ReleaseEntry release={release} key={release.version} />
        ))}
      </main>

      <footer className={styles.footnote}>
        <p>
          Releases are ordered by dependency, not scheduled to dates — a later release is blocked
          on the one before it. Scope moves between releases as work is understood. For the
          reasoning behind any item, open its issue: that is where the detail lives.
        </p>
      </footer>
    </Layout>
  );
}
