import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, statSync } from 'fs';
import path from 'path';

/**
 * The clipboard is an EXPORT destination, and issue #821 is what that costs when it is
 * forgotten.
 *
 * #673 moved every transcript download server-side so the admin `export_locked` floor is
 * consulted — and missed the clipboard, because a copy button does not look like an export.
 * `TranscriptModal` went on building the whole consolidated transcript from
 * `processedTranscriptSegments` and writing it to the clipboard with no server call at all,
 * unredacted whenever the reader had "Show original" on.
 *
 * So every surface that writes to the clipboard is enumerated here with a reason naming
 * what it copies and why that is not a policy bypass. A new one fails this test until
 * somebody answers the question. That is the same shape as the backend's
 * `tests/unit/test_export_plane_resolves_a_policy.py`: an omission is what recurs, so make
 * the omission impossible rather than trusting the next sweep to remember.
 *
 * ⚠️ This proves the surfaces are ENUMERATED, not that each is correct. What each one may
 * copy is the reason text's claim, checked by a human.
 */

const SRC = path.resolve(__dirname, '../..');

/** `<file>`: why this surface may put its text on the clipboard. */
const ALLOWED: Record<string, string> = {
  'routes/files/[id]/+page.svelte':
    'Issue #821. Does NOT serialize anything: it calls GET /files/{uuid}/export (via ' +
    'requestTranscriptExport) and copies the SERVER response, so the admin export_locked ' +
    'floor and the reader redaction policy decide the bytes, exactly as for a download.',
  'components/chat/ChatMarkdown.svelte':
    'A fenced code block out of a chat answer. The answer was already masked as it was ' +
    'generated by services/chat/output_redactor, and the clipboard copy is of what is on ' +
    'screen — no second serialization of source material.',
  'components/SummaryModal.svelte':
    'Issue #885. Does NOT serialize anything itself: it calls ' +
    'GET /files/{uuid}/summary/export (via requestSummaryExport) and copies the SERVER ' +
    'response, fed from the same masked copy GET /files/{uuid}/summary returns ' +
    '(redaction/summary_redaction.py, issue #465) — one masking implementation for both.',
  'components/ui/CopyButton.svelte':
    'The shared primitive. Copies whatever `text` prop it is handed and holds no content ' +
    'of its own; the responsibility belongs to each caller.',
  'components/mfa/MfaEnrollment.svelte':
    "MFA backup codes — the user's own freshly-minted credentials, shown once. Not " +
    'recording-derived content and unrelated to the redaction/export policy.',
  'components/settings/PromptSettings.svelte':
    'A summarization prompt template the user authored. Their own text, not transcript ' +
    'content.',
  'components/settings/SAMLSettings.svelte':
    'SP metadata / entity URLs for pasting into an IdP. Deployment configuration, not ' +
    'user content.',
  'components/settings/SecuritySettings.svelte':
    'MFA backup codes again, from the settings surface. Same reasoning as MfaEnrollment.',
  'components/upload/MediaUrlPanel.svelte':
    'READS the clipboard (navigator.clipboard.readText) to paste a media URL. Nothing ' +
    'leaves the app, so there is no export policy to consult.',
};

/** Files that define the clipboard mechanism rather than using it. */
const MECHANISM = new Set(['lib/utils/clipboard.ts']);

const CLIPBOARD_USE = /copyToClipboard\s*\(|navigator\.clipboard/;
const SCANNED_EXTENSIONS = new Set(['.svelte', '.ts', '.js']);

function walk(dir: string, found: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) {
      walk(full, found);
      continue;
    }
    if (!SCANNED_EXTENSIONS.has(path.extname(entry))) continue;
    if (/\.(test|spec)\.(ts|js)$/.test(entry)) continue;
    found.push(full);
  }
  return found;
}

function clipboardSurfaces(): string[] {
  return walk(SRC)
    .filter((file) => CLIPBOARD_USE.test(readFileSync(file, 'utf-8')))
    .map((file) => path.relative(SRC, file).split(path.sep).join('/'))
    .filter((rel) => !MECHANISM.has(rel))
    .sort();
}

describe('clipboard surfaces are enumerated (issue #821)', () => {
  it('finds the surfaces at all — a scan that matches nothing allows everything', () => {
    const surfaces = clipboardSurfaces();

    expect(surfaces.length).toBeGreaterThanOrEqual(5);
    expect(surfaces).toContain('components/ui/CopyButton.svelte');
  });

  it('every clipboard surface carries a written reason', () => {
    const unexplained = clipboardSurfaces().filter((file) => !(file in ALLOWED));

    expect(unexplained).toEqual([]);
  });

  it('no allowlist entry names a file that no longer copies anything', () => {
    const surfaces = new Set(clipboardSurfaces());
    const stale = Object.keys(ALLOWED).filter((file) => !surfaces.has(file));

    expect(stale).toEqual([]);
  });

  it('the transcript modal no longer touches the clipboard or serializes a transcript', () => {
    const modal = readFileSync(path.join(SRC, 'components/TranscriptModal.svelte'), 'utf-8');

    expect(CLIPBOARD_USE.test(modal)).toBe(false);
    expect(modal).not.toContain('consolidatedTranscript');
  });

  it('the summary modal no longer serializes a summary (issue #885)', () => {
    const modal = readFileSync(path.join(SRC, 'components/SummaryModal.svelte'), 'utf-8');

    expect(modal).not.toContain('formatSummaryAsMarkdown');
    expect(modal).not.toContain('formatCustomSummaryMarkdown');
    expect(modal).not.toContain('removeEmojis');
    expect(modal).toContain('requestSummaryExport');
  });
});
