import asyncio
import logging
import os
from contextlib import asynccontextmanager
from contextlib import suppress

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from slowapi.errors import RateLimitExceeded
from starlette.concurrency import run_in_threadpool
from starlette.responses import JSONResponse

from app.api.router import api_router
from app.auth.rate_limit import limiter
from app.auth.rate_limit import rate_limit_exceeded_handler
from app.core.config import settings
from app.core.exceptions import AuthenticationError
from app.core.exceptions import LLMServiceError
from app.core.exceptions import OpenTranscribeError
from app.core.exceptions import SearchIndexError
from app.core.exceptions import StorageError
from app.core.logging_config import configure_logging
from app.core.version import APP_VERSION
from app.middleware.audit import AuditMiddleware
from app.middleware.csrf import CSRFMiddleware
from app.middleware.observability import ObservabilityMiddleware

# Set up logging (text or structured JSON per settings.LOG_FORMAT)
configure_logging()
logger = logging.getLogger(__name__)


def _validate_production_secrets():
    """Validate that production secrets are properly configured.

    Gated on ``settings.is_hardened`` (fail-closed): every check below applies unless
    ENVIRONMENT explicitly names a relaxed environment. The previous
    ``ENVIRONMENT in ("production", "prod")`` test was never true in practice — nothing
    passes ENVIRONMENT into the containers — so none of these ran anywhere (#284 A0.3).
    """
    is_production = settings.is_hardened

    # Check JWT secret key
    insecure_jwt_secrets = (
        "this_should_be_changed_in_production",
        "changeme",
        "secret",
        "your-secret-key",
    )
    # "change_me" catches the .env.example placeholder (CHANGE_ME_auto_generated_on_install)
    # when .env was hand-copied instead of generated by the installer.
    jwt_secret = settings.JWT_SECRET_KEY.lower()
    if is_production and (jwt_secret in insecure_jwt_secrets or "change_me" in jwt_secret):
        logger.error(
            "SECURITY ERROR: JWT_SECRET_KEY is using an insecure default value in production! "
            "Set a strong, unique secret key via the JWT_SECRET_KEY environment variable."
        )
        raise ValueError("Insecure JWT_SECRET_KEY in production environment")

    # Check encryption key
    encryption_key = settings.ENCRYPTION_KEY.lower()
    if is_production and (
        "this_should_be_changed" in encryption_key or "change_me" in encryption_key
    ):
        logger.error(
            "SECURITY ERROR: ENCRYPTION_KEY is using an insecure default value in production! "
            "Set a strong, unique encryption key via the ENCRYPTION_KEY environment variable."
        )
        raise ValueError("Insecure ENCRYPTION_KEY in production environment")

    # Warn about Keycloak audience validation disabled in production
    if is_production and settings.KEYCLOAK_ENABLED and not settings.KEYCLOAK_VERIFY_AUDIENCE:
        logger.warning(
            "SECURITY WARNING: KEYCLOAK_VERIFY_AUDIENCE is disabled in production! "
            "This allows tokens intended for other clients to be accepted. "
            "Set KEYCLOAK_VERIFY_AUDIENCE=true and configure KEYCLOAK_AUDIENCE for proper token validation."
        )

    # Enforce PKI trusted proxies in production, warn in development
    if settings.PKI_ENABLED and not settings.PKI_TRUSTED_PROXIES:
        if is_production:
            logger.critical(
                "PKI_ENABLED=true but PKI_TRUSTED_PROXIES is empty! "
                "Any client can inject fake certificate headers. Refusing to start."
            )
            raise ValueError("PKI_TRUSTED_PROXIES must be set when PKI_ENABLED=true in production")
        else:
            logger.warning(
                "SECURITY WARNING: PKI_ENABLED=true but PKI_TRUSTED_PROXIES is empty! "
                "This allows any client to inject PKI certificate headers. "
                "Configure PKI_TRUSTED_PROXIES with your reverse proxy IP addresses "
                "(e.g., '127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16')."
            )

    # Check Redis password in production
    if is_production and not settings.REDIS_PASSWORD:
        logger.critical("REDIS_PASSWORD must be set in production!")
        raise ValueError("REDIS_PASSWORD is required in production environment")

    # Check debug mode in production
    if is_production and settings.DEBUG:
        logger.critical("DEBUG=true in production environment!")
        raise ValueError("DEBUG must be false in production environment")

    # Warn about insecure presigned URLs in production
    public_storage_url = settings.STORAGE_PUBLIC_URL or settings.MINIO_PUBLIC_URL
    if is_production and public_storage_url and not public_storage_url.startswith("https://"):
        logger.warning(
            "SECURITY WARNING: STORAGE_PUBLIC_URL/MINIO_PUBLIC_URL uses HTTP instead of "
            "HTTPS. Presigned URLs will be served over an insecure connection in production."
        )

    # TESTING=true enables auth shortcuts (a fabricated user, a password-free login
    # path). Enforcement lives at the USE sites in endpoints/auth.py, which additionally
    # require `not settings.is_hardened` — so the flag is inert in a real deployment even
    # if it leaks into the environment. Warn here rather than refusing to boot: the
    # secrets-guard test suite legitimately simulates production while TESTING is set
    # process-wide by conftest (issue #284 A0.8).
    if is_production and os.environ.get("TESTING", "False").lower() == "true":
        logger.warning(
            "TESTING=true in a hardened environment. Auth shortcuts are disabled by "
            "is_hardened, but this variable should not be set in production."
        )

    # A wildcard origin combined with allow_credentials=True lets any site read
    # authenticated responses. Browsers reject that pairing, but the misconfiguration
    # should surface at boot rather than as confusing CORS failures (issue #284 A0.8).
    if is_production and "*" in settings.CORS_ORIGINS:
        logger.critical(
            "CORS_ORIGINS contains '*' while credentials are allowed. "
            "Set explicit origins. Refusing to start."
        )
        raise ValueError("Wildcard CORS_ORIGINS is not permitted with credentialed requests")

    if is_production:
        logger.info("Production security validation passed")


async def _drain_websockets() -> None:
    """Close live WebSockets on shutdown so the process doesn't hang to SIGKILL.

    See ``ConnectionManager.drain`` (issue #284 A1.21). Never raises — a failure here
    must not block shutdown.
    """
    try:
        from app.api.websockets import manager

        await manager.drain()
    except Exception as e:  # noqa: BLE001 - never block shutdown on drain
        logger.warning(f"WebSocket drain failed (non-fatal): {e}")


def _setup_minio():
    """Initialize the media bucket on startup.

    Creates the media bucket if it doesn't exist and ensures the bucket
    policy is private (no anonymous/public access). All file access goes
    through presigned URLs, so public read is unnecessary and a security risk.

    Every call in here is a blocking object-storage round trip and the function never
    awaited anything, so as an ``async def`` startup task it held the event loop for
    the whole bucket bootstrap — with the API already accepting requests (issue #320).
    The lifespan now dispatches it through ``run_in_threadpool``.

    Uses the shared storage client so ``STORAGE_BACKEND=s3`` bootstraps against
    the real bucket instead of a MinIO-shaped client built from raw env vars
    (issue #284 A1.11). On native S3 the bucket is owned by the operator's
    infrastructure: we verify it and configure CORS, but never create it and
    never touch its bucket policy — a globally-unique name created in the wrong
    region, or a deleted policy, is not ours to guess at.
    """
    try:
        import json

        from app.services import storage_backend
        from app.services.minio_service import minio_client

        bucket_name = settings.MEDIA_BUCKET_NAME
        native_s3 = storage_backend.is_native_s3()

        if not minio_client.bucket_exists(bucket_name):
            if native_s3:
                logger.error(
                    f"S3 bucket '{bucket_name}' does not exist or is not reachable with the "
                    "configured credentials. Create it (and grant the role access) before "
                    "starting OpenTranscribe."
                )
                return
            minio_client.make_bucket(bucket_name)
            logger.info(f"MinIO bucket '{bucket_name}' created successfully")
        else:
            logger.info(f"Media bucket '{bucket_name}' already exists")

        # Browser-direct uploads need a bucket CORS policy on S3 (MinIO allows any
        # origin already). Opt-in and best-effort; never blocks startup.
        storage_backend.ensure_bucket_cors(bucket_name)

        # Backstop for browser-side multipart uploads the user never finished:
        # the parts of an abandoned upload are billable and invisible in a normal
        # object listing. S3 needs an explicit lifecycle rule; MinIO expires them
        # itself and refuses the rule, so this is a no-op there. Either way the
        # explicit abort on cancel/delete is the primary path.
        from app.services.multipart_upload import ensure_abort_incomplete_lifecycle

        ensure_abort_incomplete_lifecycle(bucket_name)

        if native_s3:
            return

        # Security: ensure bucket has no public access policy.
        # Previous versions set a public read policy ("Principal": {"AWS": "*"})
        # which allowed anonymous access to all stored files. Since all file
        # access goes through presigned URLs, public read is unnecessary.
        # Remove any existing public policy to lock down the bucket.
        try:
            existing_policy = minio_client.get_bucket_policy(bucket_name)
            if existing_policy:
                policy_data = json.loads(existing_policy)
                has_public_access = any(
                    stmt.get("Principal") in ({"AWS": "*"}, "*", {"AWS": ["*"]})
                    for stmt in policy_data.get("Statement", [])
                )
                if has_public_access:
                    minio_client.delete_bucket_policy(bucket_name)
                    logger.warning(
                        f"SECURITY FIX: Removed public access policy from bucket '{bucket_name}'. "
                        "All file access now requires authentication via presigned URLs."
                    )
        except Exception:  # noqa: S110
            # No policy set (expected for new buckets) — this is the secure default
            logger.debug("No bucket policy set for '%s' (secure default)", bucket_name)

    except Exception as e:
        logger.error(f"Error setting up media bucket: {e}")


def _clear_stale_task_state():
    """Clear ALL stale task state from Redis on startup.

    Any task state from the previous process lifetime is stale — the
    Celery workers that were processing it are gone. Clear everything so
    the UI starts clean and tasks can be re-triggered.

    This covers:
    - Migration orchestrator state and locks
    - Reindex coordination state and locks
    - Auto-labeling locks
    - Data integrity / embedding consistency locks
    - Search maintenance locks
    - All progress tracker keys (task_progress:*)
    """
    from app.core.redis import get_redis

    r = get_redis()

    # All migration progress services and their associated keys
    prefixes = [
        "speaker_attr_migration",
        "combined_speaker_migration",
        "embedding_migration",
    ]

    cleared = []
    for prefix in prefixes:
        suffixes = [
            ":status",
            ":batch_task_ids",
            ":orchestrator_lock",
            ":completed",
            ":lock",
        ]
        deleted_any = False
        for suffix in suffixes:
            key = f"{prefix}{suffix}"
            if r.delete(key):
                deleted_any = True
        if deleted_any:
            cleared.append(prefix)

    # Clear ALL progress tracker keys — any running task is dead after restart
    for key in r.scan_iter(match="task_progress:*"):
        r.delete(key)
        cleared.append(str(key))

    # Clear stale task locks and coordination state.
    # Every Redis-based lock used by any task must be listed here
    # so that a restart never gets blocked by an orphaned lock.
    stale_patterns = [
        # Reindex coordination
        "reindex_lock:*",
        "reindex_state:*",
        "reindex_uuids:*",
        "reindex_cancel:*",
        # Auto-labeling
        "auto_label_lock:*",
        "auto_label_progress:*",
        # Search and data integrity
        "search_maintenance_lock",
        "data_integrity_running",
        # Embedding tasks
        "normalize_embeddings_lock",
        "embedding_consistency_running",
        "embedding_consistency_progress:*",
        # Speaker clustering (TaskLockManager-based)
        "recluster_speakers_user_*",
        # Health check (TaskLockManager-based)
        "system.health_check",
    ]
    for pattern in stale_patterns:
        for key in r.scan_iter(match=pattern):
            r.delete(key)
            cleared.append(str(key))

    if cleared:
        logger.info("Cleared %d stale task keys on startup", len(cleared))


async def _run_startup_recovery():
    """Schedule startup recovery task after a delay."""
    try:
        await asyncio.sleep(10)
        from app.tasks.recovery import startup_recovery_task

        result = startup_recovery_task.delay()
        logger.info(f"Startup recovery task scheduled: {result.id}")
    except Exception as e:
        logger.error(f"Error scheduling startup recovery: {e}")


async def _run_search_maintenance():
    """Schedule search index maintenance after a delay."""
    try:
        await asyncio.sleep(30)
        from app.tasks.search_maintenance_task import search_index_maintenance_task

        result = search_index_maintenance_task.delay()
        logger.info(f"Search index maintenance task scheduled: {result.id}")
    except Exception as e:
        logger.error(f"Error scheduling search maintenance: {e}")


async def _run_thumbnail_migration():
    """Schedule thumbnail migration from JPEG to WebP after a delay."""
    try:
        await asyncio.sleep(45)  # Wait for other startup tasks
        from app.tasks.thumbnail_migration import migrate_thumbnails_to_webp

        result = migrate_thumbnails_to_webp.delay(batch_size=20)
        logger.info(f"Thumbnail migration task scheduled: {result.id}")
    except Exception as e:
        logger.error(f"Error scheduling thumbnail migration: {e}")


async def _run_imohash_recompute():
    """One-time recompute of every media_file.imohash after the package switch.

    The server-side fingerprint moved from a hand-rolled blake2b stand-in to the
    real ``imohash`` package, changing every existing value. Checks a DB flag
    first — if already done, returns immediately. Otherwise dispatches the
    batched recompute task, which sets the flag when the whole library is
    processed. Same pattern as the thumbnail / embedding-normalization
    migrations.
    """
    try:
        await asyncio.sleep(75)

        from app.db.base import SessionLocal
        from app.models.system_settings import SystemSettings
        from app.tasks.imohash_recompute import RECOMPUTE_FLAG_KEY

        db = SessionLocal()
        try:
            flag = db.query(SystemSettings).filter(SystemSettings.key == RECOMPUTE_FLAG_KEY).first()
            if flag and flag.value == "true":
                logger.info("imohash package recompute already completed — skipping")
                return
        finally:
            db.close()

        from app.tasks.imohash_recompute import recompute_all

        result = recompute_all.delay()
        logger.info(f"imohash package recompute task scheduled: {result.id}")
    except Exception as e:
        logger.error(f"Error scheduling imohash recompute: {e}")


async def _run_one_time_embedding_normalization():
    """One-time migration: normalize legacy embeddings for users upgrading.

    Checks a DB flag first — if already done, returns immediately.
    After successful normalization, sets the flag so it never runs again.
    """
    try:
        await asyncio.sleep(60)

        from app.db.base import SessionLocal
        from app.models.system_settings import SystemSettings

        db = SessionLocal()
        try:
            flag = (
                db.query(SystemSettings)
                .filter(SystemSettings.key == "embedding_normalization_done")
                .first()
            )
            if flag and flag.value == "true":
                logger.info("Embedding normalization already completed — skipping")
                return
        finally:
            db.close()

        from app.tasks.speaker_embedding_migration import normalize_speaker_embeddings_task

        result = normalize_speaker_embeddings_task.apply(throw=False)
        if result and result.result and result.result.get("normalized", 0) == 0:
            # All vectors already normalized — set flag
            db = SessionLocal()
            try:
                setting = (
                    db.query(SystemSettings)
                    .filter(SystemSettings.key == "embedding_normalization_done")
                    .first()
                )
                if not setting:
                    setting = SystemSettings(
                        key="embedding_normalization_done",
                        value="true",
                        description="One-time embedding L2 normalization migration completed",
                    )
                    db.add(setting)
                else:
                    setting.value = "true"
                db.commit()
                logger.info("Embedding normalization flag set — will not run again")
            finally:
                db.close()
        elif result and result.result:
            stats = result.result
            logger.info(
                "Embedding normalization migrated %d vectors (checked %d)",
                stats.get("normalized", 0),
                stats.get("total_found", 0),
            )
            # Set flag after successful migration
            db = SessionLocal()
            try:
                setting = SystemSettings(
                    key="embedding_normalization_done",
                    value="true",
                    description="One-time embedding L2 normalization migration completed",
                )
                db.merge(setting)
                db.commit()
            finally:
                db.close()
    except Exception as e:
        logger.error(f"Embedding normalization migration error: {e}")


# NOTE: Search settings (model ID, dimension) are now managed by OpenSearch
# neural search via ml_model_service.py and persisted in system_settings table.
# No need to load them into runtime config - they're read directly from DB when needed.


def _managed_embedding_mode() -> bool:
    """Whether the embedding model is owned by the OpenSearch domain, not by us."""
    return settings.OPENSEARCH_EMBEDDING_MODE.strip().lower() == "managed"


def _adopt_managed_embedding_model(ml_service) -> None:
    """Use an embedding model the OpenSearch domain already hosts (issue #284 A1.13).

    The default "local" path mutates ML Commons cluster settings and registers a
    model from a ``file://`` or public ``https://`` URL. Amazon OpenSearch Service
    exposes neither knob, so on a managed domain that path fails at the first
    cluster-settings PUT and neural search never comes up. In "managed" mode the
    operator has already registered the model (typically a remote-model connector),
    and all we do is adopt its id and wire the ingest pipeline.

    Synchronous: the model-id write and the ingest-pipeline PUT are both blocking
    OpenSearch calls with nothing to await (issue #320). The caller offloads it.

    Args:
        ml_service: The ``MLModelService`` singleton.
    """
    from app.services.search.indexing_service import ensure_neural_ingest_pipeline

    model_id = settings.OPENSEARCH_NEURAL_MODEL_ID.strip() or ml_service.get_active_model_id()
    if not model_id:
        logger.warning(
            "OPENSEARCH_EMBEDDING_MODE=managed but no model id is configured. Set "
            "OPENSEARCH_NEURAL_MODEL_ID to a model already registered in the domain, "
            "or set OPENSEARCH_NEURAL_SEARCH_ENABLED=false to run keyword-only search."
        )
        return

    ml_service.set_active_model_id(model_id)
    logger.info(f"Neural search using domain-managed model: {model_id}")

    if ensure_neural_ingest_pipeline():
        logger.info("Neural ingest pipeline configured successfully")
    else:
        logger.warning("Could not configure neural ingest pipeline")


async def _initialize_neural_search():
    """Initialize OpenSearch neural search models on startup.

    This function:
    1. Configures ML Commons cluster settings
    2. Checks for local models (offline deployment support)
    3. Auto-downloads default model if missing and internet available
    4. Ensures the default model is registered and deployed
    5. Creates/updates the neural ingest pipeline

    Runs after a delay to allow OpenSearch to fully start.
    For offline/air-gapped deployments, models are loaded from
    pre-downloaded local files (mounted at /ml-models in OpenSearch container).

    ``OPENSEARCH_EMBEDDING_MODE=managed`` short-circuits steps 1-4 and adopts a model
    the domain already hosts — see :func:`_adopt_managed_embedding_model`.
    """
    if not settings.OPENSEARCH_NEURAL_SEARCH_ENABLED:
        logger.info("Neural search disabled, skipping initialization")
        return

    try:
        # Wait for OpenSearch to be ready
        await asyncio.sleep(15)

        from app.services.search.ml_model_service import get_ml_model_service

        ml_service = get_ml_model_service()

        if _managed_embedding_mode():
            await run_in_threadpool(_adopt_managed_embedding_model, ml_service)
            return

        # Configure ML Commons settings
        if not ml_service.configure_ml_settings():
            logger.warning("Could not configure ML Commons settings")
            return

        # Check for available local models (offline deployment support)
        local_models = ml_service.get_available_local_models()
        if local_models:
            model_names = [m["short_name"] for m in local_models]
            logger.info(f"Found {len(local_models)} local models for offline use: {model_names}")
        else:
            logger.warning("No local models found - attempting automatic download")

            # Try to download default model if internet is available
            from app.services.search.model_downloader import check_internet_connectivity
            from app.services.search.model_downloader import ensure_model_downloaded

            default_model = settings.OPENSEARCH_NEURAL_MODEL

            if check_internet_connectivity():
                logger.info(f"Internet available - downloading default model: {default_model}")
                model_path = ensure_model_downloaded(default_model)

                if model_path:
                    logger.info(f"Model downloaded successfully: {model_path}")
                    # Re-check local models after download
                    local_models = ml_service.get_available_local_models()
                    if local_models:
                        logger.info("Models now available for offline use")
                else:
                    logger.warning("Model download failed - will use remote registration")
            else:
                logger.warning("No internet connection - cannot download models")
                logger.warning("Will use remote registration (requires OpenSearch to download)")

        # Check if we have an active model
        active_model_id = ml_service.get_active_model_id()

        if active_model_id:
            logger.info(f"Neural search already has active model: {active_model_id}")
        else:
            # Try to register and deploy the default model
            default_model = settings.OPENSEARCH_NEURAL_MODEL
            logger.info(f"No active model, attempting to setup default: {default_model}")

            # Check if default model is available locally
            local_path = ml_service.get_local_model_path(default_model)
            if local_path:
                logger.info(f"Default model available locally: {local_path}")
            else:
                logger.info("Default model not found locally, will download from remote")

            model_id = ml_service.ensure_model_deployed(default_model)
            if model_id:
                ml_service.set_active_model_id(model_id)
                logger.info(f"Default neural model deployed: {default_model} -> {model_id}")
            else:
                logger.warning(f"Could not deploy default model {default_model}")
                return

        # Ensure neural ingest pipeline is configured
        from app.services.search.indexing_service import ensure_neural_ingest_pipeline

        if ensure_neural_ingest_pipeline():
            logger.info("Neural ingest pipeline configured successfully")
        else:
            logger.warning("Could not configure neural ingest pipeline")

    except Exception as e:
        logger.error(f"Error initializing neural search: {e}")


@asynccontextmanager
async def lifespan(app: FastAPI):
    """FastAPI lifespan context manager for startup and shutdown events."""
    if os.environ.get("TESTING", "").lower() == "true":
        logger.info("Test mode: skipping startup tasks")
        yield
        return

    logger.info("Starting application...")
    _validate_production_secrets()

    # Migrations run on startup for self-host (a single container owns the DB). On
    # an orchestrated deploy a dedicated migrate Job owns them instead, and every API
    # replica racing Alembic is exactly what RUN_MIGRATIONS_ON_STARTUP=false prevents
    # (issue #284 A1.4). When gated off we do NOT silently trust the DB: readiness
    # asserts the schema is at head and fails 503 otherwise, so a replica started
    # against an un-migrated database never takes traffic.
    if settings.RUN_MIGRATIONS_ON_STARTUP:
        from app.db.migrations import run_migrations

        try:
            run_migrations()
        except Exception as e:
            logger.critical(f"Database migration failed — aborting startup: {e}")
            raise SystemExit(1) from e
    else:
        logger.info(
            "RUN_MIGRATIONS_ON_STARTUP=false — skipping migrations; a migrate job is "
            "expected to own them. Readiness will verify the schema is at head."
        )

    # Seed initial data (admin user, default tags, system prompts)
    try:
        from app.db.base import SessionLocal
        from app.initial_data import init_db

        db = SessionLocal()
        try:
            init_db(db)
        finally:
            db.close()
    except Exception as e:
        logger.warning(f"Initial data seeding failed (non-fatal): {e}")

    # Check OpenSearch index health (auto-repair corrupted shards from unclean shutdowns).
    #
    # ensure_*_exist are idempotent no-ops once the indices are there, so every replica
    # may run them. check_and_repair_indices is NOT cheap and acts on shared cluster
    # state, so it is elected — N replicas repairing the same indices concurrently is
    # wasted work at best (issue #284 A1.15).
    try:
        from app.services.opensearch_service import check_and_repair_indices
        from app.services.opensearch_service import ensure_indices_exist
        from app.services.opensearch_service import ensure_v4_index_exists
        from app.utils.boot_once import run_once_per_boot

        ensure_indices_exist()
        ensure_v4_index_exists()
        if run_once_per_boot("opensearch_repair_indices"):
            check_and_repair_indices()
    except Exception as e:
        logger.warning(f"OpenSearch startup health check failed (non-fatal): {e}")

    # Sync speaker profile data from PostgreSQL to OpenSearch
    try:
        from app.db.base import SessionLocal
        from app.services.opensearch_service import sync_speaker_profiles_to_opensearch

        _db = SessionLocal()
        try:
            sync_result = sync_speaker_profiles_to_opensearch(_db)
            if sync_result["updated"] > 0:
                logger.info(f"Speaker profile sync: {sync_result}")
        finally:
            _db.close()
    except Exception as e:
        logger.warning(f"Speaker profile sync failed (non-fatal): {e}")

    # Apply the admin-configured derived-cache retention (DB over env) so the MinIO
    # lifecycle rule reflects UI changes after a restart — no redeploy needed. Also
    # run a one-time reclaim of pre-prefix (legacy) derived assets for upgraders.
    try:
        from app.db.base import SessionLocal
        from app.services import cache_management_service
        from app.services import system_settings_service

        _db = SessionLocal()
        try:
            days = cache_management_service.apply_retention(_db)
            logger.info(f"Derived-cache retention applied: {days} day(s)")

            reclaimed_key = "cache.legacy_derived_reclaimed"
            if not system_settings_service.get_setting_bool(_db, reclaimed_key, False):
                count = cache_management_service.reclaim_legacy_derived_cache()
                system_settings_service.set_setting(
                    _db,
                    reclaimed_key,
                    True,
                    "One-time reclaim of pre-prefix derived cache objects has run",
                )
                if count:
                    logger.info(f"Upgrade reclaim: removed {count} legacy derived cache object(s)")
        finally:
            _db.close()
    except Exception as e:
        logger.warning(f"Derived-cache retention/reclaim setup failed (non-fatal): {e}")

    # Clear stale migration state from Redis (orphaned by unclean shutdown).
    #
    # Elected, because this deletes ALL task_progress:* keys and every coordination
    # lock. Unelected, the second replica to boot wipes progress and locks belonging to
    # work the first replica is actively coordinating (issue #284 A1.3).
    try:
        from app.utils.boot_once import run_once_per_boot

        if run_once_per_boot("clear_stale_task_state"):
            _clear_stale_task_state()
    except Exception as e:
        logger.warning(f"Migration state cleanup failed (non-fatal): {e}")

    logger.info("Setting up MinIO and task recovery...")
    minio_task = asyncio.create_task(run_in_threadpool(_setup_minio))
    recovery_task = asyncio.create_task(_run_startup_recovery())
    search_maintenance = asyncio.create_task(_run_search_maintenance())
    thumbnail_migration = asyncio.create_task(_run_thumbnail_migration())
    neural_search_task = asyncio.create_task(_initialize_neural_search())
    embedding_migration = asyncio.create_task(_run_one_time_embedding_normalization())
    imohash_recompute_task = asyncio.create_task(_run_imohash_recompute())

    yield

    logger.info("Shutting down application...")

    await _drain_websockets()

    for task in [
        minio_task,
        recovery_task,
        search_maintenance,
        thumbnail_migration,
        neural_search_task,
        embedding_migration,
        imohash_recompute_task,
    ]:
        if not task.done():
            task.cancel()
            with suppress(asyncio.CancelledError):
                await task


# Create FastAPI app with lifespan and consistent routing configuration
app = FastAPI(
    title=settings.PROJECT_NAME,
    description="Audio transcription and analysis API",
    version=APP_VERSION,
    openapi_url=f"{settings.API_PREFIX}/openapi.json",
    docs_url=f"{settings.API_PREFIX}/docs",
    redoc_url=f"{settings.API_PREFIX}/redoc",
    lifespan=lifespan,
    # Disable redirect_slashes to prevent 307 redirects that expose Docker internal hostnames
    # Routes should be defined with "" (not "/") to match paths without trailing slash
    redirect_slashes=False,
    # Increase default timeout to 1 hour for large file uploads
    default_timeout=3600,
)

# Set up CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allow_headers=[
        "Content-Type",
        "Authorization",
        "Accept",
        "Accept-Language",
        "X-Request-ID",
        "X-CSRF-Token",
    ],
)

# Configure maximum upload size (50GB)
app.router.default_max_upload_size = 50 * 1024 * 1024 * 1024  # type: ignore[attr-defined]  # 50GB

# Add Audit Middleware for request ID tracking (FedRAMP AU-2/AU-3)
app.add_middleware(AuditMiddleware)

# CSRF protection for cookie-based authentication (C2 security hardening)
app.add_middleware(CSRFMiddleware)

# Observability MUST be the LAST add_middleware call so it runs OUTERMOST.
# Starlette semantics (verified 0.48.0): add_middleware does
# `user_middleware.insert(0, ...)` and the stack is built over `reversed(...)`,
# so the LAST-added middleware is the OUTERMOST — NOT the add-call order. The
# resulting runtime order is: Observability -> CSRF -> Audit -> CORS -> router.
# That lets us record CSRF 403 rejections plus every routed request, and read
# request.state.{request_id,user_id,client_ip} (set by inner layers during
# call_next on the shared scope) after call_next returns. Do NOT "fix" the
# order by reordering these calls.
app.add_middleware(ObservabilityMiddleware)


# Global handler for the application exception hierarchy.
# Maps domain-specific exceptions to appropriate HTTP status codes so that
# any ``OpenTranscribeError`` raised in endpoint code is automatically
# serialised as a structured JSON response.
#
# Deliberately `async def` even though it never awaits, which is the one shape the
# issue #320 sweep leaves alone: the body is a dict lookup and a JSONResponse
# construction, with no I/O to block the loop. Starlette does accept a plain `def`
# handler, but it dispatches one through `run_in_threadpool`, so declaring it `def`
# would buy a thread hop on every error response and free nothing.
@app.exception_handler(OpenTranscribeError)
async def handle_app_error(request, exc: OpenTranscribeError):
    status_map = {
        AuthenticationError: 401,
        StorageError: 503,
        SearchIndexError: 503,
        LLMServiceError: 502,
    }
    status = status_map.get(type(exc), 500)
    return JSONResponse(
        status_code=status,
        content={"detail": exc.message},
    )


# Include the API router
app.include_router(api_router, prefix=settings.API_PREFIX)

# Set up rate limiting
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, rate_limit_exceeded_handler)  # type: ignore[arg-type]


# Prometheus scrape endpoint, mounted at ROOT (no API_PREFIX) next to /health.
# Unauthenticated by design — nginx denies it and the host port is LAN-only.
from app.api.endpoints.metrics import router as metrics_router  # noqa: E402

app.include_router(metrics_router)


# Health check endpoint
@app.get("/health")
def health_check():
    """Health check endpoint"""
    return {"status": "healthy", "version": APP_VERSION}


@app.get("/health/ready")
def readiness_check():
    """Readiness probe for load balancers / orchestrators.

    Probes the critical dependencies (PostgreSQL, Redis) and the degraded-but-
    serviceable ones (OpenSearch, MinIO). A failed CRITICAL dependency returns
    503; OpenSearch/MinIO failures are reported but do not fail readiness, since
    queued transcription survives a brief search/storage outage. Plain ``def``
    so Starlette threadpools the short, synchronous probes.
    """
    from sqlalchemy import text

    checks: dict[str, str] = {}

    # PostgreSQL (critical) — short-lived session, SELECT 1.
    try:
        from app.db.base import SessionLocal

        db = SessionLocal()
        try:
            db.execute(text("SELECT 1"))
            checks["postgres"] = "ok"
        finally:
            db.close()
    except Exception as exc:  # noqa: BLE001
        checks["postgres"] = f"error: {type(exc).__name__}"

    # Redis (critical) — ping the shared db-0 singleton.
    try:
        from app.core.redis import get_redis

        get_redis().ping()
        checks["redis"] = "ok"
    except Exception as exc:  # noqa: BLE001
        checks["redis"] = f"error: {type(exc).__name__}"

    # OpenSearch (degraded-but-ready) — reuse the existing client singleton.
    try:
        from app.services.opensearch_service import get_opensearch_client

        client = get_opensearch_client()
        if client is not None and client.ping():
            checks["opensearch"] = "ok"
        else:
            checks["opensearch"] = "unavailable"
    except Exception as exc:  # noqa: BLE001
        checks["opensearch"] = f"error: {type(exc).__name__}"

    # MinIO (degraded-but-ready) — reuse the existing client singleton.
    try:
        from app.services.minio_service import minio_client

        minio_client.bucket_exists(settings.MEDIA_BUCKET_NAME)
        checks["minio"] = "ok"
    except Exception as exc:  # noqa: BLE001
        checks["minio"] = f"error: {type(exc).__name__}"

    # Schema freshness (critical) — only when a migrate job owns migrations. If this
    # replica did not run Alembic itself, it must prove the DB is actually at head
    # before taking traffic; otherwise a rollout that outpaces the migrate job serves
    # requests against an old schema (issue #284 A1.4).
    if not settings.RUN_MIGRATIONS_ON_STARTUP:
        try:
            from alembic.migration import MigrationContext
            from alembic.script import ScriptDirectory

            from app.db.base import engine
            from app.db.migrations import get_alembic_config

            head = ScriptDirectory.from_config(get_alembic_config()).get_current_head()
            with engine.connect() as conn:
                current = MigrationContext.configure(conn).get_current_revision()
            checks["schema"] = "ok" if current == head else f"stale: {current} != head {head}"
        except Exception as exc:  # noqa: BLE001
            checks["schema"] = f"error: {type(exc).__name__}"

    critical_ok = (
        checks["postgres"] == "ok"
        and checks["redis"] == "ok"
        and checks.get("schema", "ok") == "ok"
    )
    if not critical_ok:
        return JSONResponse(
            status_code=503,
            content={"status": "not_ready", "checks": checks},
        )
    return {"status": "ready", "checks": checks}


# Static files are served by nginx in production, not by FastAPI
# Removed conflicting static file mounting to prevent nginx conflicts

# Run the application if executed directly
if __name__ == "__main__":
    import uvicorn

    # Binding to 0.0.0.0 is required for Docker containers
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=True)  # noqa: S104 # nosec B104
